<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SpendTracker</AssemblyName>
    <OutputType>WinExe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpendTracker.Domain\SpendTracker.Domain.csproj" />
    <ProjectReference Include="..\SpendTracker.Infrastructure\SpendTracker.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\**" />
    <EmbeddedResource Include="wwwroot\index.html" />
    <EmbeddedResource Include="wwwroot\app.js" />
    <EmbeddedResource Include="wwwroot\styles.css" />
  </ItemGroup>

</Project>
